-- Schéma complet et migration idempotente du challenge collaboratif.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null,
  slot smallint not null unique check (slot between 1 and 5),
  created_at timestamptz not null default now()
);

alter table public.profiles drop constraint if exists profiles_slot_check;
alter table public.profiles add constraint profiles_slot_check check (slot between 1 and 5);

create table if not exists public.department_entries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  department_code text not null,
  visited boolean not null default false,
  photo_url text,
  photo_path text,
  photo_date date,
  comment text not null default '',
  visit_date date,
  updated_at timestamptz not null default now(),
  unique (user_id, department_code)
);

create or replace function public.create_challenge_profile()
returns trigger
language plpgsql
security definer set search_path = public
as $$
declare
  available_slot smallint;
begin
  select candidate.slot into available_slot
  from (values (1::smallint), (2::smallint), (3::smallint), (4::smallint), (5::smallint)) as candidate(slot)
  where not exists (select 1 from public.profiles where slot = candidate.slot)
  order by candidate.slot
  limit 1;

  if available_slot is null then
    raise exception 'Ce challenge possède déjà ses cinq membres.';
  end if;

  insert into public.profiles (id, display_name, slot)
  values (
    new.id,
    coalesce(nullif(new.raw_user_meta_data ->> 'display_name', ''), split_part(new.email, '@', 1)),
    available_slot
  );
  return new;
end;
$$;

drop trigger if exists on_challenge_user_created on auth.users;
create trigger on_challenge_user_created
  after insert on auth.users
  for each row execute function public.create_challenge_profile();

alter table public.profiles enable row level security;
alter table public.department_entries enable row level security;

drop policy if exists "members read profiles" on public.profiles;
create policy "members read profiles" on public.profiles
  for select to authenticated using (true);

drop policy if exists "public read profiles" on public.profiles;
create policy "public read profiles" on public.profiles
  for select to anon using (true);

drop policy if exists "members read entries" on public.department_entries;
create policy "members read entries" on public.department_entries
  for select to authenticated using (true);

drop policy if exists "public read entries" on public.department_entries;
create policy "public read entries" on public.department_entries
  for select to anon using (true);

drop policy if exists "members add their entries" on public.department_entries;
create policy "members add their entries" on public.department_entries
  for insert to authenticated with check (auth.uid() = user_id);

drop policy if exists "members update their entries" on public.department_entries;
create policy "members update their entries" on public.department_entries
  for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "members delete their entries" on public.department_entries;
create policy "members delete their entries" on public.department_entries
  for delete to authenticated using (auth.uid() = user_id);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'prefecture-photos',
  'prefecture-photos',
  true,
  10485760,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "members upload their photos" on storage.objects;
create policy "members upload their photos" on storage.objects
  for insert to authenticated
  with check (
    bucket_id = 'prefecture-photos'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

drop policy if exists "members read their photo metadata" on storage.objects;
create policy "members read their photo metadata" on storage.objects
  for select to authenticated
  using (
    bucket_id = 'prefecture-photos'
    and owner_id = (select auth.uid()::text)
  );

drop policy if exists "members update their photos" on storage.objects;
create policy "members update their photos" on storage.objects
  for update to authenticated
  using (bucket_id = 'prefecture-photos' and owner_id = (select auth.uid()::text))
  with check (bucket_id = 'prefecture-photos' and owner_id = (select auth.uid()::text));

drop policy if exists "members delete their photos" on storage.objects;
create policy "members delete their photos" on storage.objects
  for delete to authenticated
  using (bucket_id = 'prefecture-photos' and owner_id = (select auth.uid()::text));
